# Copyright (c) 2026 1abcdefggs (takaer)
# Licensed under the MIT License
# See LICENSE file in the project root for full license information

name: Publish Release

on:
  push:
    tags:
      - 'v*' # Triggers when a version tag like v0.2.1 is pushed
      workflow_dispatch: #

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Permission required to create a GitHub Release
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build VSIX Package
        run: npx @vscode/vsce package --no-dependencies

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: "*.vsix"
          generate_release_notes: true # Automatically generates release notes based on commit history
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
